# Generated by Django 4.1.7 on 2023-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='blogger', max_length=50)),
                ('password', models.SlugField()),
                ('profilePic', models.URLField(default='https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_1280.png')),
            ],
        ),
    ]
