# Generated by Django 4.1.7 on 2023-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
